# Generated by Django 3.2.9 on 2021-11-21 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_auto_20211121_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueBook',
            new_name='Issue',
        ),
    ]
