# Generated by Django 3.2.7 on 2021-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_borrower_issue_borrower_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='copy_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
