# Generated by Django 3.2.7 on 2021-12-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20211215_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issuer_id',
            new_name='issuer',
        ),
    ]
