# Generated by Django 3.2.7 on 2021-12-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20211215_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='floor',
            field=models.CharField(default=10, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.CharField(default=10, max_length=4),
            preserve_default=False,
        ),
    ]
